### ISSUE TITLE
Archmage Blood Orb and Reinforced Teleposition Focus recipe conflict

### ISSUE THREAD

**Issue by reserveword** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#139] opened 2020-12-30 16:42 UTC
**General Info (please complete the following information):**
 - Modpack version: 3.4.1
 - Client or server: server
 - Own modifications to the modpack:

**Describe the bug**
this two recipe
![图片](https://user-images.githubusercontent.com/12995615/103367586-792ce280-4b00-11eb-9005-b8b42a4c58b4.png)
![图片](https://user-images.githubusercontent.com/12995615/103367595-7e8a2d00-4b00-11eb-8622-c690b0132944.png)
are conflict, so I can't make Archmage Blood Orb.

**To Reproduce**
1. Build a Blood Altar, grade V
2. give it enough LP constantly
3. put a nether star in it
4. wait for Archmage Blood Orb to be crafted
5. but it becomes Reinforced Teleposition Focus and stops there.
6. maybe we can add a recipe of [Reinforced Teleposition Focus]=>[Archmage Blood Orb]?

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]

**Comment by saovenn** [comment] 2020-12-30 17:01
Hello and thank you for your report

This problem is already fixed in 3.4.0 (#106 )

Can you please verify that your scripts are up to date

**Comment by reserveword** [comment] 2021-01-07 15:07
I'm still confused. I watched that #106 , but it seems to have deleted [teleportaion focus => reinforced teleportaion focus] recipe and added [nether star => reinforced teleportaion focus] recipe. Isn't it the *cause* of this issue rather than a *solve* for this issue?
And sure I am running 3.4.1, my BloodMagic.zs looks like
```
mods.bloodmagic.BloodAltar.removeRecipe(<bloodmagic:teleposition_focus>);
mods.bloodmagic.BloodAltar.addRecipe(<bloodmagic:teleposition_focus:1>, <minecraft:nether_star>, 3, 10000, 10, 10);
```
and it is the same as branch master (or branch 3.4.x)

**Comment by saovenn** [comment] 2021-01-19 11:43
sorry for the late response

These recipes are adapted from the 1.7.10 Infinity Evolved Expert Mode

Starting with Enhanced Teleposition Focus, you have to do some "upgrade crafting" - this is intended

The normal Teleportation Focus is only available for the Teleposer recipe and 1x1x1 teleportation

**Comment by reserveword** [comment] 2021-01-19 13:21
I am not a native speaker, so pardon me if I misunderstood.

> Starting with Enhanced Teleposition Focus, you have to do some "upgrade crafting" - this is intended
> 
If you mean that in Expert Mode we have to pay more than it original costs to get Enhanced Teleposition Focus, I would say you are right. But the problem is this recipe overwrites the recipe for Archmage Blood Orb, so we can't obtain Archmage Blood Orb at all.

I would propose my solution down there:

Add a recipe: 
`mods.bloodmagic.BloodAltar.addRecipe(<bloodmagic:blood_orb>.withTag({orb: "bloodmagic:archmage"}), <minecraft:nether_star>, 4, 70000, 10, 10);`
which allows player to make Archmage Blood Orb from Enhanced Teleposition Focus, with the same altar and blood requirements (70000+10000=80000).

I am not famillar with zenscript so please correct me if I made something wrong.

**Comment by saovenn** [comment] 2021-01-19 13:34
Ahhh - I will adjust the recipe, now I know exactly what the problem is, thank you 👍 ^^

**Closed** 2021-03-05 16:21 UTC
Labels: bug
